### ISSUE TITLE
Missing package dependency v2.0.2 onwards

### ISSUE THREAD

**Issue by harshil1507** [trayio/graphql-query-to-json#59]
When trying to run the example from the readme, running into this error. 

Happens only when package version >= 2.0.2, works well with 2.0.1

```
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module 'json-to-graphql-query'
```

**Comment by thomaschaplin** [comment]
@harshil1507 thank you for raising this issue alongside a PR to fix it. I've merged your PR and will release a new version. I have also raised a new issue to investigate the long term vision of how we handle this going forwards based on @rickschubert observations.

See https://github.com/trayio/graphql-query-to-json/issues/61
